---
abstract: 'Secure conversion of CGI params hash to SQL'
author:
  - 'Alex Efros <powerman@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-SecureCGI
provides:
  DBIx::SecureCGI:
    file: lib/DBIx/SecureCGI.pm
    version: v2.0.3
requires:
  AnyEvent: 0
  AnyEvent::DBI::MySQL: 1.000002
  DBD::mysql: 0
  DBI: 0
  perl: v5.10.0
  version: 0.77
resources:
  license: http://www.opensource.org/licenses/mit-license.php
version: v2.0.3
