---
abstract: 'Secure conversion of CGI params hash to SQL'
author:
  - 'Alex Efros <powerman@cpan.org>'
build_requires:
  Pod::Coverage: '0.18'
  Test::CheckManifest: '0.9'
  Test::Exception: '0'
  Test::More: '0'
  Test::Perl::Critic: '0'
  Test::Pod: '1.22'
  Test::Pod::Coverage: '1.08'
configure_requires:
  Module::Build: '0.4004'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.140640'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DBIx-SecureCGI
provides:
  DBIx::SecureCGI:
    file: lib/DBIx/SecureCGI.pm
    version: v2.0.7
requires:
  AnyEvent: '0'
  AnyEvent::DBI::MySQL: v1.0.2
  DBD::mysql: '0'
  DBI: '0'
  perl: '5.01'
  version: '0.77'
resources:
  license: http://www.opensource.org/licenses/mit-license.php
version: v2.0.7
